### ISSUE TITLE
Preload skips 6-10/10 completely even when there are missing blocks

### ISSUE THREAD

**Issue by PoohVz** [planetarium/libplanet#1497]
![image](https://user-images.githubusercontent.com/13524523/133922854-2fa38641-2d34-4185-b28f-d5c22752a9bb.png)

[logs.zip](https://github.com/planetarium/libplanet/files/7191682/logs.zip)
[logs1.zip](https://github.com/planetarium/libplanet/files/7191684/logs1.zip)

Restart the launcher multiple times won't do anything.
This usually is fixed after clearing cache.

**Comment by area363** [comment]
This was due to the snapshot file error which has been resolved so I am closing this issue 🙏 @PoohVz

**Comment by PoohVz** [comment]
@area363 it's still happening now, there are a lot of reports on discord

**Comment by PoohVz** [comment]
oh wait wrong one
